#version 450

layout(local_size_x = 64) in;
layout(set = 0, binding = 0, std430) readonly buffer A { float values[]; } a;
layout(set = 0, binding = 1, std430) readonly buffer B { float values[]; } b;
layout(set = 0, binding = 2, std430) writeonly buffer Output { float values[]; } output_data;
layout(push_constant) uniform Parameters { uint count; } parameters;

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i >= parameters.count) return;
  precise float value = a.values[i] + b.values[i];
  output_data.values[i] = value;
}
