# Validate one checked-in shader artifact and optionally export its byte array.
# No compiler invocation occurs here: source/binary pairs remain reproducible,
# pinned artifacts produced by the documented shader build tools.
function(slopfab_shader relative_path expected_hash kind output_variable)
  set(shader_path "${CMAKE_CURRENT_SOURCE_DIR}/${relative_path}")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${shader_path}")
  string(LENGTH "${expected_hash}" hash_length)
  if(NOT hash_length EQUAL 64 OR NOT expected_hash MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "slopfab: malformed shader hash for ${relative_path}")
  endif()
  if(kind STREQUAL "SOURCE")
    file(READ "${shader_path}" source_text)
    string(REPLACE "\r\n" "\n" source_text "${source_text}")
    string(SHA256 actual_hash "${source_text}")
  elseif(kind STREQUAL "BINARY")
    file(SHA256 "${shader_path}" actual_hash)
  else()
    message(FATAL_ERROR "slopfab: unknown shader artifact kind ${kind}")
  endif()
  if(NOT actual_hash STREQUAL expected_hash)
    message(FATAL_ERROR
      "slopfab: shader/source hash mismatch: ${relative_path}; regenerate with "
      "the pinned compiler/tool and update its manifest")
  endif()
  if(NOT output_variable STREQUAL "-")
    file(READ "${shader_path}" shader_hex HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," shader_bytes "${shader_hex}")
    set(${output_variable} "${shader_bytes}" PARENT_SCOPE)
  endif()
endfunction()

macro(slopfab_reference_shaders)
  set(reference_manifest "${CMAKE_CURRENT_SOURCE_DIR}/src/vulkan/reference.sha256")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${reference_manifest}")
  file(STRINGS "${reference_manifest}" reference_hashes)
  list(LENGTH reference_hashes reference_hash_count)
  if(NOT reference_hash_count EQUAL 2)
    message(FATAL_ERROR "slopfab: malformed reference shader manifest")
  endif()
  list(GET reference_hashes 0 reference_source_hash)
  list(GET reference_hashes 1 reference_binary_hash)
  slopfab_shader(src/vulkan/tensor_reference.comp "${reference_source_hash}" SOURCE -)
  slopfab_shader(src/vulkan/tensor_reference.comp.spv "${reference_binary_hash}"
    BINARY SLOPFAB_TENSOR_REFERENCE_SPV_BYTES)
endmacro()

macro(slopfab_fast_attention_shaders)
  set(fast_manifest "${CMAKE_CURRENT_SOURCE_DIR}/src/vulkan/attention_fast.sha256")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${fast_manifest}")
  file(STRINGS "${fast_manifest}" fast_hashes)
  set(SLOPFAB_SAGE_VARIANT_DECLARATIONS "")
  foreach(fast_entry IN LISTS fast_hashes)
    string(REGEX MATCH "^([0-9a-f]+)  (.+)$" matched_entry "${fast_entry}")
    if(NOT matched_entry)
      message(FATAL_ERROR "slopfab: malformed fast attention shader manifest")
    endif()
    set(fast_hash "${CMAKE_MATCH_1}")
    set(fast_file "${CMAKE_MATCH_2}")
    if(fast_file MATCHES "\\.comp$")
      slopfab_shader("src/vulkan/${fast_file}" "${fast_hash}" SOURCE -)
    else()
      if(NOT fast_file MATCHES "^tensor_attention_(.+)\\.comp\\.spv$")
        message(FATAL_ERROR "slopfab: unknown fast attention binary ${fast_file}")
      endif()
      string(TOUPPER "${CMAKE_MATCH_1}" fast_variant)
      set(fast_output "SLOPFAB_TENSOR_ATTENTION_${fast_variant}_SPV_BYTES")
      slopfab_shader("src/vulkan/${fast_file}" "${fast_hash}" BINARY "${fast_output}")
      if(NOT fast_variant MATCHES "^(FLASH|FLASH_BANDED|SAGE|SAGE_BANDED|SAGE_PREPARE)$")
        string(APPEND SLOPFAB_SAGE_VARIANT_DECLARATIONS
          "inline constexpr uint8_t kTensorAttention_${fast_variant}[] = {${${fast_output}}};\n")
      endif()
    endif()
  endforeach()
endmacro()
